version: '3.1'

volumes:
  uma-volumeiii:
  uma-volumeii:

services:
  web1:
    build: rasa
    ports:
      - "5015:5015"
    volumes:
      - uma-volumeiii:/usr/src/app/bot

  web2:
    build: rasa-x
    ports:
      - "5012:5012"
    volumes:
      - uma-volumeiii:/usr/src/app/bot
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: (boquito&selma321)
    volumes:
      - uma-volumeii:/data/db
  

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8082
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: paulista
      ME_CONFIG_BASICAUTH_PASSWORD: (gordalove456)
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: (boquito&selma321)

  web3:
    build: twilio_hook
    volumes:
      - ./twilio_hook/app:/app
    ports:
      - "5011:5011"
    environment:
      - FLASK_APP=bot.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=5001'
    command: flask run --host=0.0.0.0 --port=5001      
